---
- name: Install GitLab
  # hosts: gitlabci_server
  hosts: ext_gitlabci_server
  become: yes
  vars_files:
    - vars/default_vars.yml

  tasks:

    - name: Check if GitLab is already installed
      stat: path=/usr/bin/gitlab-ctl
      register: gitlab_file

    - name: Install required dependencies for GitLab
      apt:
        name: "{{ gitlab_dependencies }}"
        state: present
        update_cache: yes

    - name: Add the GitLab package repository (Debian)
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
      args:
        warn: no
      when: not gitlab_file.stat.exists

    - name: Install GitLab
      apt:
        name: gitlab-ce
        state: present

    - name: Copy GitLab configuration file
      template:
        src: "gitlab.rb.j2"
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0600

    - name: Reconfigure GitLab
      command:
        cmd: gitlab-ctl reconfigure
        creates: /var/opt/gitlab/bootstrapped
      # failed_when: false
...
